from __future__ import annotations

"""Bootstrap + core service (module 11, spec §127.1 / §134.1).

`CoreService.start()` is the idempotent bootstrap the whole CLI sits on:

    creator keypair  ->  event log  ->  projections  ->  registry

Idempotency (a §127.1 hard requirement: "second restart is idempotent (no
duplicate events)"): the M1 seed providers are registered with events ONLY on
the first start. On every later start the registry is reconstructed from the
`capability.provider_added` / `provider_revoked` projection WITHOUT appending
anything, so the registry "reflects exactly the seeded providers, no
agent-registered ones".

The pairing code is generated by the CLI (`jarvis init`), not persisted: M1
has no pairing consumer yet (disclosed — the code is printed, nothing
completes a pairing handshake).
"""

import os
import secrets
from pathlib import Path

from .kernel.creator import CreatorIdentity
from .kernel.event_log import Event, EventLog
from .kernel.memory_projection import MemoryProjection
from .kernel.registry import (
    CREATOR_PRINCIPAL_ID,
    CapabilityRegistry,
    ProviderBinding,
)
from .observability import configure_otel

PROVIDER_ADDED = "capability.provider_added"
SERVICE_STARTED = "system.service_started"

_PAIRING_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def default_home() -> Path:
    return Path(os.environ.get("JARVIS_HOME", "~/.jarvis")).expanduser()


def new_pairing_code() -> str:
    """XXXX-XXXX, ambiguity-free alphabet. Random, not persisted."""
    raw = "".join(secrets.choice(_PAIRING_ALPHABET) for _ in range(8))
    return f"{raw[:4]}-{raw[4:]}"


class CoreService:
    """Loads (or creates) creator identity, event log, projections, registry."""

    def __init__(
        self, home: Path | str | None = None, *, observer: object | None = None
    ) -> None:
        self.home = Path(home).expanduser() if home is not None else default_home()
        self.log_path = self.home / "log.db"
        self._observer = observer
        self.identity: CreatorIdentity | None = None
        self.log: EventLog | None = None
        self.registry: CapabilityRegistry | None = None
        self._projection: MemoryProjection | None = None

    def start(self) -> "CoreService":
        self.home.mkdir(parents=True, exist_ok=True)
        self.identity = CreatorIdentity.create(self.home / "keys")
        observer = self._observer or configure_otel()
        self.log = EventLog(db_path=self.log_path, observer=observer)
        self._projection = MemoryProjection.rebuild(self.log)
        if self._already_seeded():
            self.registry = self._registry_from_projection(self._projection)
        else:
            self.registry = CapabilityRegistry.seed_m1_defaults(log=self.log)
            self._projection = MemoryProjection.rebuild(self.log)
        return self

    # ---- accessors --------------------------------------------------------

    @property
    def fingerprint(self) -> str:
        assert self.identity is not None, "CoreService.start() not called"
        return self.identity.fingerprint()

    def projection(self) -> MemoryProjection:
        assert self._projection is not None, "CoreService.start() not called"
        return self._projection

    def provider_ids(self) -> list[str]:
        return self.projection().provider_ids()

    def close(self) -> None:
        if self.log is not None:
            self.log.close()
            self.log = None

    def __enter__(self) -> "CoreService":
        return self.start()

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    # ---- internals --------------------------------------------------------

    def _already_seeded(self) -> bool:
        assert self.log is not None
        return any(
            event.event_type == PROVIDER_ADDED for event in self.log.replay()
        )

    @staticmethod
    def _registry_from_projection(projection: MemoryProjection) -> CapabilityRegistry:
        """Rebuild in-memory registry from the log projection, no new events."""
        registry = CapabilityRegistry(log=None)
        for provider_id in projection.provider_ids():
            registry.register_provider(
                CREATOR_PRINCIPAL_ID,
                ProviderBinding.model_validate(projection.providers[provider_id]),
            )
        return registry


def ensure_service_started(log: EventLog) -> bool:
    """Idempotently record `system.service_started`. Returns True iff appended.

    Backs the §127.1 `core service started` line with a durable event; re-running
    `jarvis init` on the same home appends nothing further.
    """
    if any(event.event_type == SERVICE_STARTED for event in log.replay()):
        return False
    log.append(
        Event(
            stream_id="system",
            event_type=SERVICE_STARTED,
            principal_id=CREATOR_PRINCIPAL_ID,
            payload={"service": "core", "pid_scope": "one_shot"},
        )
    )
    return True
